version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      - SIH_DB_PATH=/app/data/sih.db
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    environment:
      - SIH_BACKEND_URL=http://backend:8000/api/v1
      - MAPBOX_TOKEN=
    depends_on:
      - backend
